#!/usr/bin/env sh

scons -j8 no-cache=1 with-maya=2014
scons -j8 no-cache=1 with-maya=2015
scons -j8 no-cache=1 with-maya=2016 with-mayadevkit=/usr/autodesk/maya2016/devkitBase
scons -j8 no-cache=1 with-maya=2017 with-mayadevkit=/usr/autodesk/maya2017/devkitBase

