# MGEAR is under the terms of the MIT License

# Copyright (c) 2016 Jeremie Passerin, Miquel Campos

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Author:     Jeremie Passerin      geerem@hotmail.com  www.jeremiepasserin.com
# Author:     Miquel Campos         hello@miquel-campos.com  www.miquel-campos.com
# Date:       2016 / 10 / 10

import mgear.maya.pyqt as gqt
QtGui, QtCore, QtWidgets, wrapInstance = gqt.qt_import()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 546)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(1, 2, 331, 101))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 311, 74))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.rigName_label = QtWidgets.QLabel(self.widget)
        self.rigName_label.setObjectName("rigName_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rigName_label)
        self.rigName_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.rigName_lineEdit.setObjectName("rigName_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rigName_lineEdit)
        self.mode_label = QtWidgets.QLabel(self.widget)
        self.mode_label.setObjectName("mode_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mode_label)
        self.mode_comboBox = QtWidgets.QComboBox(self.widget)
        self.mode_comboBox.setObjectName("mode_comboBox")
        self.mode_comboBox.addItem("")
        self.mode_comboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mode_comboBox)
        self.step_label = QtWidgets.QLabel(self.widget)
        self.step_label.setObjectName("step_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.step_label)
        self.step_comboBox = QtWidgets.QComboBox(self.widget)
        self.step_comboBox.setObjectName("step_comboBox")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.step_comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.step_comboBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 103, 331, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 311, 50))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importSkin_checkBox = QtWidgets.QCheckBox(self.widget1)
        self.importSkin_checkBox.setObjectName("importSkin_checkBox")
        self.verticalLayout.addWidget(self.importSkin_checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.skin_label = QtWidgets.QLabel(self.widget1)
        self.skin_label.setObjectName("skin_label")
        self.horizontalLayout.addWidget(self.skin_label)
        self.skin_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.skin_lineEdit.setObjectName("skin_lineEdit")
        self.horizontalLayout.addWidget(self.skin_lineEdit)
        self.loadSkinPath_pushButton = QtWidgets.QPushButton(self.widget1)
        self.loadSkinPath_pushButton.setObjectName("loadSkinPath_pushButton")
        self.horizontalLayout.addWidget(self.loadSkinPath_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(1, 182, 331, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.jointRig_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.jointRig_checkBox.setGeometry(QtCore.QRect(10, 17, 151, 17))
        self.jointRig_checkBox.setObjectName("jointRig_checkBox")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(1, 225, 331, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget2 = QtWidgets.QWidget(self.groupBox_4)
        self.widget2.setGeometry(QtCore.QRect(10, 18, 311, 181))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rigTabs_label = QtWidgets.QLabel(self.widget2)
        self.rigTabs_label.setObjectName("rigTabs_label")
        self.verticalLayout_3.addWidget(self.rigTabs_label)
        self.rigTabs_listWidget = QtWidgets.QListWidget(self.widget2)
        self.rigTabs_listWidget.setDragDropOverwriteMode(True)
        self.rigTabs_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.rigTabs_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.rigTabs_listWidget.setAlternatingRowColors(True)
        self.rigTabs_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.rigTabs_listWidget.setSelectionRectVisible(False)
        self.rigTabs_listWidget.setObjectName("rigTabs_listWidget")
        self.verticalLayout_3.addWidget(self.rigTabs_listWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.addTab_pushButton = QtWidgets.QPushButton(self.widget2)
        self.addTab_pushButton.setObjectName("addTab_pushButton")
        self.verticalLayout_4.addWidget(self.addTab_pushButton)
        self.removeTab_pushButton = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeTab_pushButton.sizePolicy().hasHeightForWidth())
        self.removeTab_pushButton.setSizePolicy(sizePolicy)
        self.removeTab_pushButton.setObjectName("removeTab_pushButton")
        self.verticalLayout_4.addWidget(self.removeTab_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.available_label = QtWidgets.QLabel(self.widget2)
        self.available_label.setObjectName("available_label")
        self.verticalLayout_2.addWidget(self.available_label)
        self.available_listWidget = QtWidgets.QListWidget(self.widget2)
        self.available_listWidget.setDragDropOverwriteMode(True)
        self.available_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.available_listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.available_listWidget.setAlternatingRowColors(True)
        self.available_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.available_listWidget.setSelectionRectVisible(False)
        self.available_listWidget.setObjectName("available_listWidget")
        self.verticalLayout_2.addWidget(self.available_listWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(2, 438, 331, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.widget3 = QtWidgets.QWidget(self.groupBox_5)
        self.widget3.setGeometry(QtCore.QRect(10, 20, 311, 71))
        self.widget3.setObjectName("widget3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.L_color_fk_label = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label.setObjectName("L_color_fk_label")
        self.horizontalLayout_3.addWidget(self.L_color_fk_label)
        self.L_color_fk_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_color_fk_spinBox.sizePolicy().hasHeightForWidth())
        self.L_color_fk_spinBox.setSizePolicy(sizePolicy)
        self.L_color_fk_spinBox.setMaximum(31)
        self.L_color_fk_spinBox.setObjectName("L_color_fk_spinBox")
        self.horizontalLayout_3.addWidget(self.L_color_fk_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.L_color_fk_label_5 = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label_5.setObjectName("L_color_fk_label_5")
        self.horizontalLayout_7.addWidget(self.L_color_fk_label_5)
        self.C_color_fk_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C_color_fk_spinBox.sizePolicy().hasHeightForWidth())
        self.C_color_fk_spinBox.setSizePolicy(sizePolicy)
        self.C_color_fk_spinBox.setMaximum(31)
        self.C_color_fk_spinBox.setObjectName("C_color_fk_spinBox")
        self.horizontalLayout_7.addWidget(self.C_color_fk_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.L_color_fk_label_3 = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label_3.setObjectName("L_color_fk_label_3")
        self.horizontalLayout_5.addWidget(self.L_color_fk_label_3)
        self.R_color_fk_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_color_fk_spinBox.sizePolicy().hasHeightForWidth())
        self.R_color_fk_spinBox.setSizePolicy(sizePolicy)
        self.R_color_fk_spinBox.setMaximum(31)
        self.R_color_fk_spinBox.setObjectName("R_color_fk_spinBox")
        self.horizontalLayout_5.addWidget(self.R_color_fk_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.L_color_fk_label_2 = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label_2.setObjectName("L_color_fk_label_2")
        self.horizontalLayout_4.addWidget(self.L_color_fk_label_2)
        self.L_color_ik_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_color_ik_spinBox.sizePolicy().hasHeightForWidth())
        self.L_color_ik_spinBox.setSizePolicy(sizePolicy)
        self.L_color_ik_spinBox.setMaximum(31)
        self.L_color_ik_spinBox.setObjectName("L_color_ik_spinBox")
        self.horizontalLayout_4.addWidget(self.L_color_ik_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.L_color_fk_label_6 = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label_6.setObjectName("L_color_fk_label_6")
        self.horizontalLayout_8.addWidget(self.L_color_fk_label_6)
        self.C_color_ik_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C_color_ik_spinBox.sizePolicy().hasHeightForWidth())
        self.C_color_ik_spinBox.setSizePolicy(sizePolicy)
        self.C_color_ik_spinBox.setMaximum(31)
        self.C_color_ik_spinBox.setObjectName("C_color_ik_spinBox")
        self.horizontalLayout_8.addWidget(self.C_color_ik_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.L_color_fk_label_4 = QtWidgets.QLabel(self.widget3)
        self.L_color_fk_label_4.setObjectName("L_color_fk_label_4")
        self.horizontalLayout_6.addWidget(self.L_color_fk_label_4)
        self.R_color_ik_spinBox = QtWidgets.QSpinBox(self.widget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_color_ik_spinBox.sizePolicy().hasHeightForWidth())
        self.R_color_ik_spinBox.setSizePolicy(sizePolicy)
        self.R_color_ik_spinBox.setMaximum(31)
        self.R_color_ik_spinBox.setObjectName("R_color_ik_spinBox")
        self.horizontalLayout_6.addWidget(self.R_color_ik_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.groupBox.setTitle(gqt.fakeTranslate("Form", "Rig Settings", None, -1))
        self.rigName_label.setText(gqt.fakeTranslate("Form", "Rig Name", None, -1))
        self.mode_label.setText(gqt.fakeTranslate("Form", "Debug Mode", None, -1))
        self.mode_comboBox.setItemText(0, gqt.fakeTranslate("Form", "Final", None, -1))
        self.mode_comboBox.setItemText(1, gqt.fakeTranslate("Form", "WIP", None, -1))
        self.step_label.setText(gqt.fakeTranslate("Form", "Step", None, -1))
        self.step_comboBox.setItemText(0, gqt.fakeTranslate("Form", "All Steps", None, -1))
        self.step_comboBox.setItemText(1, gqt.fakeTranslate("Form", "Objects", None, -1))
        self.step_comboBox.setItemText(2, gqt.fakeTranslate("Form", "Attributes", None, -1))
        self.step_comboBox.setItemText(3, gqt.fakeTranslate("Form", "Operators", None, -1))
        self.step_comboBox.setItemText(4, gqt.fakeTranslate("Form", "Connect", None, -1))
        self.step_comboBox.setItemText(5, gqt.fakeTranslate("Form", "Joints", None, -1))
        self.step_comboBox.setItemText(6, gqt.fakeTranslate("Form", "Finalize", None, -1))
        self.groupBox_2.setTitle(gqt.fakeTranslate("Form", "Skinning Settings", None, -1))
        self.importSkin_checkBox.setText(gqt.fakeTranslate("Form", "Import Skin", None, -1))
        self.skin_label.setText(gqt.fakeTranslate("Form", "Skin Path", None, -1))
        self.loadSkinPath_pushButton.setText(gqt.fakeTranslate("Form", "Load Path", None, -1))
        self.groupBox_3.setTitle(gqt.fakeTranslate("Form", "Joint Settings", None, -1))
        self.jointRig_checkBox.setText(gqt.fakeTranslate("Form", "Separated Joint Structure", None, -1))
        self.groupBox_4.setTitle(gqt.fakeTranslate("Form", "Synoptic Settings", None, -1))
        self.rigTabs_label.setText(gqt.fakeTranslate("Form", "Rig Tabs", None, -1))
        self.addTab_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.removeTab_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))
        self.available_label.setText(gqt.fakeTranslate("Form", "Available Tabs", None, -1))
        self.groupBox_5.setTitle(gqt.fakeTranslate("Form", "Color Settings", None, -1))
        self.label.setText(gqt.fakeTranslate("Form", "Left", None, -1))
        self.label_2.setText(gqt.fakeTranslate("Form", "Center", None, -1))
        self.label_3.setText(gqt.fakeTranslate("Form", "Right", None, -1))
        self.L_color_fk_label.setText(gqt.fakeTranslate("Form", "FK", None, -1))
        self.L_color_fk_label_5.setText(gqt.fakeTranslate("Form", "FK", None, -1))
        self.L_color_fk_label_3.setText(gqt.fakeTranslate("Form", "FK", None, -1))
        self.L_color_fk_label_2.setText(gqt.fakeTranslate("Form", "IK", None, -1))
        self.L_color_fk_label_6.setText(gqt.fakeTranslate("Form", "IK", None, -1))
        self.L_color_fk_label_4.setText(gqt.fakeTranslate("Form", " IK", None, -1))

