# MGEAR is under the terms of the MIT License

# Copyright (c) 2016 Jeremie Passerin, Miquel Campos

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Author:     Jeremie Passerin      geerem@hotmail.com  www.jeremiepasserin.com
# Author:     Miquel Campos         hello@miquel-campos.com  www.miquel-campos.com
# Date:       2016 / 10 / 10

import mgear.maya.pyqt as gqt
QtGui, QtCore, QtWidgets, wrapInstance = gqt.qt_import()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 524)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.channelMapping_tableWidget = QtWidgets.QTableWidget(Form)
        self.channelMapping_tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.channelMapping_tableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.channelMapping_tableWidget.setAlternatingRowColors(True)
        self.channelMapping_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.channelMapping_tableWidget.setCornerButtonEnabled(False)
        self.channelMapping_tableWidget.setObjectName("channelMapping_tableWidget")
        self.channelMapping_tableWidget.setColumnCount(4)
        self.channelMapping_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.channelMapping_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.channelMapping_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.channelMapping_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.channelMapping_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.channelMapping_tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.export_pushButton = QtWidgets.QPushButton(Form)
        self.export_pushButton.setObjectName("export_pushButton")
        self.horizontalLayout.addWidget(self.export_pushButton)
        self.import_pushButton = QtWidgets.QPushButton(Form)
        self.import_pushButton.setObjectName("import_pushButton")
        self.horizontalLayout.addWidget(self.import_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.apply_pushButton = QtWidgets.QPushButton(Form)
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.verticalLayout.addWidget(self.apply_pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel_lineEdit.sizePolicy().hasHeightForWidth())
        self.channel_lineEdit.setSizePolicy(sizePolicy)
        self.channel_lineEdit.setObjectName("channel_lineEdit")
        self.horizontalLayout_2.addWidget(self.channel_lineEdit)
        self.channel_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.channel_pushButton.setObjectName("channel_pushButton")
        self.horizontalLayout_2.addWidget(self.channel_pushButton)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.target_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_lineEdit.sizePolicy().hasHeightForWidth())
        self.target_lineEdit.setSizePolicy(sizePolicy)
        self.target_lineEdit.setObjectName("target_lineEdit")
        self.horizontalLayout_3.addWidget(self.target_lineEdit)
        self.target_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.target_pushButton.setObjectName("target_pushButton")
        self.horizontalLayout_3.addWidget(self.target_pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.setRow_pushButton = QtWidgets.QPushButton(Form)
        self.setRow_pushButton.setObjectName("setRow_pushButton")
        self.verticalLayout_2.addWidget(self.setRow_pushButton)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.setMultiChannel_pushButton = QtWidgets.QPushButton(Form)
        self.setMultiChannel_pushButton.setObjectName("setMultiChannel_pushButton")
        self.verticalLayout_2.addWidget(self.setMultiChannel_pushButton)
        self.setMultiTarget_pushButton = QtWidgets.QPushButton(Form)
        self.setMultiTarget_pushButton.setObjectName("setMultiTarget_pushButton")
        self.verticalLayout_2.addWidget(self.setMultiTarget_pushButton)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.autoPopulate_pushButton = QtWidgets.QPushButton(Form)
        self.autoPopulate_pushButton.setObjectName("autoPopulate_pushButton")
        self.verticalLayout_2.addWidget(self.autoPopulate_pushButton)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.clearSelectedRows_pushButton = QtWidgets.QPushButton(Form)
        self.clearSelectedRows_pushButton.setObjectName("clearSelectedRows_pushButton")
        self.verticalLayout_2.addWidget(self.clearSelectedRows_pushButton)
        self.clearAll_pushButton = QtWidgets.QPushButton(Form)
        self.clearAll_pushButton.setObjectName("clearAll_pushButton")
        self.verticalLayout_2.addWidget(self.clearAll_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.channelMapping_tableWidget.setSortingEnabled(True)
        self.channelMapping_tableWidget.horizontalHeaderItem(0).setText(gqt.fakeTranslate("Form", "Channel", None, -1))
        self.channelMapping_tableWidget.horizontalHeaderItem(1).setText(gqt.fakeTranslate("Form", "Source", None, -1))
        self.channelMapping_tableWidget.horizontalHeaderItem(2).setText(gqt.fakeTranslate("Form", "Target", None, -1))
        self.channelMapping_tableWidget.horizontalHeaderItem(3).setText(gqt.fakeTranslate("Form", "operation", None, -1))
        self.export_pushButton.setText(gqt.fakeTranslate("Form", "Export", None, -1))
        self.import_pushButton.setText(gqt.fakeTranslate("Form", "Import", None, -1))
        self.apply_pushButton.setText(gqt.fakeTranslate("Form", "Apply", None, -1))
        self.groupBox.setTitle(gqt.fakeTranslate("Form", "Channel", None, -1))
        self.channel_pushButton.setText(gqt.fakeTranslate("Form", "<<<", None, -1))
        self.groupBox_2.setTitle(gqt.fakeTranslate("Form", "Target", None, -1))
        self.target_pushButton.setText(gqt.fakeTranslate("Form", "<<<", None, -1))
        self.setRow_pushButton.setText(gqt.fakeTranslate("Form", "Set Row", None, -1))
        self.setMultiChannel_pushButton.setText(gqt.fakeTranslate("Form", "Set Multi Channel", None, -1))
        self.setMultiTarget_pushButton.setText(gqt.fakeTranslate("Form", "Set Multi Target", None, -1))
        self.autoPopulate_pushButton.setText(gqt.fakeTranslate("Form", "Auto Populate", None, -1))
        self.clearSelectedRows_pushButton.setText(gqt.fakeTranslate("Form", "Clear Selected Rows", None, -1))
        self.clearAll_pushButton.setText(gqt.fakeTranslate("Form", "Clear All", None, -1))
